# -*- coding: utf-8 -*-
"""emotion_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T0GIoQt7MGIr86r9COqsYxGHjws1WmKt
"""

import requests

def emotion_detector(text_to_analyse):
    """
    This function sends text to Watson NLP Emotion Detection API
    and returns the detected emotions.
    """

    url = "https://sn-watson-emotion.labs.skills.network/v1/watson.runtime.nlp.v1/NlpService/EmotionPredict"

    headers = {
        "grpc-metadata-mm-model-id": "emotion_aggregated-workflow_lang_en_stock"
    }

    json_data = {
        "raw_document": {
            "text": text_to_analyse
        }
    }

    response = requests.post(url, json=json_data, headers=headers)

    if response.status_code == 200:
        return response.json()
    else:
        return None